# Generated by Django 5.1.4 on 2025-01-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='grade',
            new_name='wares',
        ),
    ]
