# Generated by Django 5.1.4 on 2025-01-28 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='добавьте название')),
                ('description', models.TextField(verbose_name='добавьте описание')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='наименование ингредиента')),
                ('quantity', models.PositiveIntegerField(verbose_name='укажите количество')),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs')], max_length=5, verbose_name='выберите ед. измерения')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
