# Generated by Django 5.1.4 on 2025-01-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0005_reviews_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('checked', models.CharField(choices=[('Done', 'Done'), ('Not completed', 'Not completed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.books')),
            ],
        ),
    ]
